[package]
name = "czkawka_core"
version = "1.5.1"
authors = ["Rafa≈Ç Mikrut <mikrutrafal@protonmail.com>"]
edition = "2018"
description = "Core of Czkawka app"
license = "MIT"
homepage = "https://github.com/qarmin/czkawka"
repository = "https://github.com/qarmin/czkawka"


[dependencies]
humansize = "1"
blake3 = "0.3"
rayon = "1"
crossbeam-channel = "0.4.4"


# Needed by similar images
img_hash = "3.1"
bk-tree = "0.3"
image = "0.23"
hamming = "0.1"

# Needed by same music
bitflags = "1.2.1"
audiotags = "0.2.7182"

# Futures - needed by async progress sender
futures = "0.3.8"