[package]
name = "czkawka_core"
version = "3.3.1"
authors = ["Rafa≈Ç Mikrut <mikrutrafal@protonmail.com>"]
edition = "2018"
description = "Core of Czkawka app"
license = "MIT"
homepage = "https://github.com/qarmin/czkawka"
repository = "https://github.com/qarmin/czkawka"


[dependencies]
humansize = "1.1.1"
rayon = "1.5.1"
crossbeam-channel = "0.5.1"

# For saving/loading config files to specific directories
directories-next = "2.0.0"

# Needed by similar images
img_hash = "3.2.0"
bk-tree = "0.4.0"
image = "0.23.14"
hamming = "0.1.3"

# Needed by same music
bitflags = "1.3.2"
audiotags = "0.2.7182"

# Futures - needed by async progress sender
futures = "0.3.17"

# Needed by broken files
zip = "0.5.13"
rodio = { version = "0.14.0", optional = true }

# Hashes
blake3 = "1.2.0"
crc32fast = "1.2.1"
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }

tempfile = "3.2.0"

[features]
default = []

broken_audio = ["rodio"]
