[package]
name = "czkawka_core"
version = "4.0.0"
authors = ["Rafa≈Ç Mikrut <mikrutrafal@protonmail.com>"]
edition = "2021"
description = "Core of Czkawka app"
license = "MIT"
homepage = "https://github.com/qarmin/czkawka"
repository = "https://github.com/qarmin/czkawka"


[dependencies]
humansize = "1.1.1"
rayon = "1.5.1"
crossbeam-channel = "0.5.4"

# For saving/loading config files to specific directories
directories-next = "2.0.0"

# Needed by similar images
image_hasher = "1.0.0"
bk-tree = "0.4.0"
image = "0.24.1"
hamming = "0.1.3"

# Needed by same music
bitflags = "1.3.2"
lofty="0.5.3"

# Futures - needed by async progress sender
futures = "0.3.21"

# Needed by broken files
zip = "0.6.1"
rodio = { version = "0.15.0", optional = true }

# Hashes for duplicate files
blake3 = "1.3.1"
crc32fast = "1.3.2"
xxhash-rust = { version = "0.8.4", features = ["xxh3"] }

tempfile = "3.3.0"

# Video Duplactes
vid_dup_finder_lib = "0.1.0"
ffmpeg_cmdline_utils = "0.1.1"

# Saving/Loading Cache
serde = "1.0.133"
bincode = "1.3.3"
serde_json = "1.0.74"

# Language
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.1"
rust-embed = "6.3.0"
once_cell = "1.9.0"

# Raw image files
rawloader = "0.37.0"
imagepipe = "0.4.0"


[features]
default = []

broken_audio = ["rodio"]
