[package]
name = "czkawka_cli"
version = "4.0.0"
authors = ["Rafa≈Ç Mikrut <mikrutrafal@protonmail.com>"]
edition = "2018"
description = "CLI frontend of Czkawka"
license = "MIT"
homepage = "https://github.com/qarmin/czkawka"
repository = "https://github.com/qarmin/czkawka"

[dependencies]
czkawka_core = { path = "../czkawka_core", version = "4.0.0" }
structopt = "0.3.25"

# For enum types
img_hash = "3.2.0"