[package]
name = "czkawka_cli"
version = "3.3.1"
authors = ["Rafa≈Ç Mikrut <mikrutrafal@protonmail.com>"]
edition = "2018"
description = "CLI frontend of Czkawka"
license = "MIT"
homepage = "https://github.com/qarmin/czkawka"
repository = "https://github.com/qarmin/czkawka"

[dependencies]
czkawka_core = { path = "../czkawka_core" }
structopt = "0.3.25"

# For enum types
img_hash = "3.2.0"