[package]
name = "czkawka_cli"
version = "5.1.0"
authors = ["Rafa≈Ç Mikrut <mikrutrafal@protonmail.com>"]
edition = "2021"
rust-version = "1.65.0"
description = "CLI frontend of Czkawka"
license = "MIT"
homepage = "https://github.com/qarmin/czkawka"
repository = "https://github.com/qarmin/czkawka"

[dependencies]
clap = { version = "4.1", features = ["derive"] }

# For enum types
image_hasher = "1.1.2"

[dependencies.czkawka_core]
path = "../czkawka_core"
version = "5.1.0"
features = []

[features]
default = []
heif = ["czkawka_core/heif"]
